* CS556-Project 2

** Overview
   This project is focused on creating a UI and a tool that supports the instructor's model of 
   Multiparty Authorization System for relational databases.
   
** Installation
#+begin_src shell
python3 -m venv local_env

source local_env/bin/activate

pip install -r requirments.txt
#+end_src

** Project Team
   - Vedaant Rajoo (vrajoo@purdue.edu)

** Objectives
   - [ ] Administrative Delegation
   - [ ] Administrative Transfer
   - [ ] Recursive Revoke
   - [ ] Grantor Transfer
   - [ ] With acceptance
   - [ ] w/o acceptance
   - [ ] Change the GUI system

** TODO
   - [X] Create a basic schema and implement the database into Python
   - [X] Figure out the implementation of the UI
   - [X] Add DBA users to admin privilege.
   - [X] Backend Development
   - [X] Figure out the realtional connections.
   - [X] Add AuthLogin graph class to main app
   - [] Package App
   - [X] Logs Screen
   - [X] Add the logs to the database


** Report Worthy

Using networkx library to create and manage graphs for admistritrative and Authorization.
Using pythonQT6 to create a UI for the database.
Changing the GUI Interface to TKInter.
Using GRANT and REVOKE from SQL to manage permisssions.
Tables -> user_info, PAB, obj_info.
